# permissions for end users to view brokers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: broker-viewer-role
rules:
- apiGroups:
  - broker.bcandido.com
  resources:
  - brokers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - broker.bcandido.com
  resources:
  - brokers/status
  verbs:
  - get
