# permissions for end users to edit topics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topic-editor-role
rules:
- apiGroups:
  - broker.bcandido.com
  resources:
  - topics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - broker.bcandido.com
  resources:
  - topics/status
  verbs:
  - get
