apiVersion: broker.bcandido.com/v1alpha1
kind: Broker
metadata:
  name: local-kafka

spec:
  name: local-kafka
  type: kafka
  configuration:
    bootstrapServers:
      - 10.1.29.77:9092
      - 10.1.29.83:9092
      - 10.1.29.89:9092
